[package]
name = "LarsonClip"
version = "0.1.0"
edition = "2021"

[dependencies]
device_query = "1.1.0"
windows-capture = "1.3.2"
anyhow = "1.0"
thiserror = "1.0.63"
lz4 = "1.26.0"
windows = "0.58.0"
lazy_static = "1.5.0"
reqwest = { version = "0.12.7", features = ["blocking", "multipart", "json"] }
serde_json = "1.0"
libobs = "0.1.3"

[dev-dependencies]
tempfile = "3.12.0"

[profile.release]
debug = true
