[package]
name = "Mebal"
version = "0.1.2"
edition = "2021"
description = "An OS independent replay buffer solution."
license = "MIT"
authors = ["Brody Larson <brody@larson.dev>"]
repository = "https://github.com/lurkny/Mebal"

[dependencies]
anyhow = "1.0"
lz4_flex = { version = "0.11", default-features = false }
reqwest = { version = "0.12.7", features = ["blocking", "multipart", "json"] }
serde_json = "1.0"
rayon = "1.10.0"
rdev = "0.5.1"

[target.'cfg(target_os = "windows")'.dependencies]
win_desktop_duplication = "0.10.11"
windows = "0.58.0"
windows-capture = "1.3.2"

[target.'cfg(not(target_os = "windows"))'.dependencies]
scrap = "0.5"

[dev-dependencies]
tempfile = "3.12.0"

[profile.release]
lto = true           # Full LTO for cross-crate optimization
opt-level = 3        # Aggressive optimizations
codegen-units = 1    # Maximum optimization potential
strip = true         # Remove debug symbols
panic = "abort"      # Smaller, faster panic handling
