[package]
name = "LarsonClip"
version = "0.1.0"
edition = "2021"

[dependencies]
windows-capture = "1.3.2"
anyhow = "1.0"
lz4 = "1.26.0"
windows = "0.58.0"
reqwest = { version = "0.12.7", features = ["blocking", "multipart", "json"] }
serde_json = "1.0"
scrap = "0.5.0"
rayon = "1.10.0"
rdev = "0.5.1"



[dev-dependencies]
tempfile = "3.12.0"

[profile.release]
debug = true
