[package]
name = "common"
version = "0.1.0"
edition = "2024"

[dependencies]
ffmpeg-next = { workspace = true }
anyhow = { workspace = true }
log = { workspace = true }
tokio = { workspace = true }
async-trait = { workspace = true }
