[package]
name = "recorder"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.45.1", features = ["full"] }
async-trait = "0.1"
storage = { path = "../storage" }
common = {path = "../common" }
